### ISSUE TITLE
browersync loads forever

### ISSUE THREAD

**Issue by astrocycles** [mnyorba/generator-wordpress-s-theme#28]
Hi,
I'm using node 6.10.3. When enter gulp command browersync opens in a new tab ( localhost 8000), but the theme never loads.

thanks for your help

**Comment by mnyorba** [comment]
Hi
The theme will be reloaded after saving the changes in the * .scss or * .php theme files.

**Comment by astrocycles** [comment]
sorry doesn't seem to work

**Comment by mnyorba** [comment]
Was the wordpress installation complete? The generator sets only the wordpress theme and works with it.

**Comment by astrocycles** [comment]
yes the theme loads from the WP backend.

**Comment by mnyorba** [comment]
If you installed the generator according to the description that should work - I use it myself)
I should note that I work for Windows
If you want, I'm ready to try to help solve the problem and see through remote access (such as TeamViewer).

**Comment by astrocycles** [comment]
yes thanks that 's really kind of you. My skype is olietstomp. I'll give you my teamviewer credential in the chat.

many thanks
